lab 3
DiachT/KotlinLabsNUZP pull request #94
Opened 2023-10-16 12:08 UTC by Malnormalulos-git

2023-10-17 15:50 UTC, Malnormalulos-git commented
Чому саме ті масиви лінкувалися наче зрозумів, важко сформолювати, тому наведу приклад:
data class pStr (   // Pointer to a String
  var s:String=""
)

fun main() {
 var st=pStr("banana")
 var tt=st
 tt.s = "melon"
 println(st.s) // display "melon"

 var s:String = "banana"
 var t:String = s
 t.s = "melon"
 println(s.s) // display "banana"
}

2023-10-17 15:51 UTC, Malnormalulos-git commented
А от авто тест тут щось завалює, хоча в мене локально на машині тести проходять ¯\_(ツ)_/¯

2023-10-18 10:34 UTC, DiachT requested changes

2023-10-18 10:34 UTC, DiachT commented on modules/common/src/main/kotlin/com/diacht/ktest/Product.kt
> +data class Product(val type: ProductType, var count: Int)
Будь ласка, не порушуйте принцип іммутабельності, в складних системах, це призводить до великих багів.  у data-класі не рекомедується використовувати var.

2023-10-18 11:02 UTC, DiachT commented
тести пройшли, але є зауваження. використовувайте Product.copy(...)

2023-10-18 11:02 UTC, closed without merging